### ISSUE TITLE
Feature request: EnumerateProcessor

### ISSUE THREAD

**Issue by Melevir** [best-doctor/import_me#4]
csv/xlsx data often has enum fields, that are stored as integers or strings. Now we should parse raw data, than map them to appropriate enum.

It would be nice to have processor, that does all that mapping logic.

**Comment by morgangt** [comment]
i suggest this solution
https://github.com/best-doctor/import_me/pull/9

**Comment by Melevir** [comment]
Enumerate fields should process should process columns with values like, for example `RUB` and `USD`, but as a result return not strings, but values of enum

```
class Currency(Enumerate):
    rub = 1
    usd = 2
```

So it seem like we should feed to EnumerateProcessor mapping like `{'RUB': Currency.rub, 'USD': Currency.usd}` and receive enum values as column values.

**Comment by Melevir** [comment]
Done by @Valerich. Thanks!
